# Generated by Django 5.1.1 on 2024-12-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supportticket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("resolved", "Resolved")],
                default="active",
                max_length=20,
            ),
        ),
    ]
