# Generated by Django 5.1.1 on 2025-01-03 05:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("supportticket", "0002_supportticket_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supportticket",
            old_name="case_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="supportticket",
            old_name="case_title",
            new_name="title",
        ),
    ]
