# Generated by Django 5.1.1 on 2024-12-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['-created_at']},
        ),
    ]
