# Generated by Django 5.1.1 on 2024-12-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_ticket_options_alter_ticketmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_individual',
            field=models.BooleanField(default=False),
        ),
    ]
