# Generated by Django 5.1.1 on 2025-01-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0003_ticket_is_individual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("resolved", "Resolved")],
                default="active",
                max_length=20,
            ),
        ),
    ]
