# Generated by Django 5.1.1 on 2025-01-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0004_alter_ticket_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("in_progress", "In_progress"),
                    ("reopened", "Reopened"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
