# Generated by Django 5.1.1 on 2024-09-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_membership_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="xp",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
