# Generated by Django 5.1.1 on 2024-10-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_remove_company_members_customuser_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
