# Generated by Django 5.1.1 on 2024-10-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_alter_customuser_profile_picture_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="first_name",
            field=models.CharField(default="john", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invitation",
            name="last_name",
            field=models.CharField(default="doe", max_length=50),
            preserve_default=False,
        ),
    ]
