# Generated by Django 5.1.1 on 2024-10-08 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySteps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_count", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Streak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timeStamp", models.DateTimeField(auto_now_add=True)),
                ("currentStreak", models.IntegerField(default=0)),
                ("highestStreak", models.IntegerField(default=0)),
                ("currentStreakSaver", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration", models.IntegerField()),
                ("xp", models.FloatField()),
                ("activityType", models.CharField(max_length=50)),
                ("activityName", models.CharField(max_length=100)),
                ("distance", models.FloatField(blank=True, default=0.0, null=True)),
                ("avgBpm", models.FloatField(blank=True, default=0.0, null=True)),
                ("metadata", models.TextField(blank=True, null=True)),
                ("startDate", models.DateTimeField()),
                ("endDate", models.DateTimeField()),
                ("currentDate", models.DateField(auto_now_add=True)),
                ("deviceType", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_activity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Xp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timeStamp", models.DateTimeField(auto_now_add=True)),
                ("totalXpToday", models.FloatField(default=0.0)),
                ("totalXpAllTime", models.FloatField(default=0.0)),
                ("currentXpRemaining", models.FloatField(default=0.0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
