# Generated by Django 5.1.1 on 2024-10-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_dailysteps_streak_workoutactivity_xp"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailysteps",
            name="xp",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
