# Generated by Django 5.1.1 on 2024-10-09 06:40

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_dailysteps_xp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(default="UTC"),
        ),
    ]
