# Generated by Django 5.1.1 on 2024-10-09 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_customuser_timezone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workoutactivity",
            old_name="activityName",
            new_name="activity_name",
        ),
        migrations.RenameField(
            model_name="workoutactivity",
            old_name="activityType",
            new_name="activity_type",
        ),
        migrations.RenameField(
            model_name="workoutactivity",
            old_name="avgBpm",
            new_name="average_heart_rate",
        ),
        migrations.RenameField(
            model_name="workoutactivity",
            old_name="currentDate",
            new_name="current_date",
        ),
        migrations.RenameField(
            model_name="workoutactivity",
            old_name="endDate",
            new_name="end_datetime",
        ),
        migrations.RenameField(
            model_name="workoutactivity",
            old_name="startDate",
            new_name="start_datetime",
        ),
    ]
