# Generated by Django 5.1.1 on 2024-10-10 13:05

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_rename_activityname_workoutactivity_activity_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(default="UTC", use_pytz=False),
        ),
    ]
