# Generated by Django 5.1.1 on 2024-10-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0013_alter_customuser_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutactivity",
            name="current_date",
            field=models.DateField(),
        ),
    ]
