# Generated by Django 5.1.1 on 2024-10-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0015_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
