# Generated by Django 5.1.1 on 2024-10-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0016_purchase_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="tickets",
            new_name="company_tickets",
        ),
        migrations.AddField(
            model_name="customuser",
            name="global_tickets",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="streak_savers",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
