# Generated by Django 5.1.1 on 2024-10-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0018_draw_drawentry_prize_drawwinner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="xp_used",
        ),
        migrations.AlterUniqueTogether(
            name="xp",
            unique_together={("user", "timeStamp")},
        ),
        migrations.AddField(
            model_name="customuser",
            name="gem",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gems_spent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="purchase",
            name="gem_used",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="xp",
            name="gems_awarded",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="xp",
            name="currentXpRemaining",
        ),
    ]
