# Generated by Django 5.1.1 on 2024-10-19 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0019_remove_purchase_xp_used_alter_xp_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="draw",
            old_name="name",
            new_name="draw_name",
        ),
    ]
