# Generated by Django 5.1.1 on 2024-10-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0022_remove_workoutactivity_current_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="prize",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="draw_videos/"),
        ),
    ]
