# Generated by Django 5.1.1 on 2024-10-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0023_prize_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prize",
            name="video",
        ),
        migrations.AddField(
            model_name="draw",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="draw_videos/"),
        ),
    ]
