# Generated by Django 5.1.1 on 2024-10-26 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0025_league_leagueinstance_companyleagueinstance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyleagueinstance",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.league",
            ),
        ),
        migrations.AddField(
            model_name="leagueinstance",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
