# Generated by Django 5.1.1 on 2024-10-26 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0027_alter_customuser_league"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userleague",
            old_name="xp",
            new_name="xp_company",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="league",
        ),
        migrations.RemoveField(
            model_name="leagueinstance",
            name="is_company",
        ),
        migrations.AddField(
            model_name="leagueinstance",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.company",
            ),
        ),
        migrations.AddField(
            model_name="userleague",
            name="xp_global",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="CompanyLeagueInstance",
        ),
    ]
