# Generated by Django 5.1.1 on 2024-10-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0031_streak_date_alter_streak_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xp",
            name="timeStamp",
            field=models.DateTimeField(),
        ),
    ]
