# Generated by Django 5.1.1 on 2024-11-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0033_alter_dailysteps_xp_alter_workoutactivity_xp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailysteps",
            name="xp",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="workoutactivity",
            name="xp",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="xp",
            name="totalXpAllTime",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="xp",
            name="totalXpToday",
            field=models.FloatField(default=0.0),
        ),
    ]
