# Generated by Django 5.1.1 on 2024-11-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0037_gem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="gem",
        ),
        migrations.AlterField(
            model_name="gem",
            name="manual_gem",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="gem",
            name="xp_gem",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
