# Generated by Django 5.1.1 on 2024-11-18 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0038_remove_customuser_gem_alter_gem_manual_gem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="company_tickets",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="global_tickets",
        ),
    ]
