# Generated by Django 5.1.1 on 2024-11-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0039_remove_customuser_company_tickets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gem",
            name="copy_manual_gem",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="gem",
            name="copy_xp_gem",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
