# Generated by Django 5.1.1 on 2024-12-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0041_drawimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawimage",
            name="image_link",
            field=models.URLField(max_length=255),
        ),
    ]
