# Generated by Django 5.1.1 on 2024-12-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0043_notif"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="xp",
        ),
        migrations.AlterField(
            model_name="leagueinstance",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="leagueinstance",
            name="league_end",
            field=models.DateTimeField(db_index=True),
        ),
    ]
