# Generated by Django 5.1.1 on 2024-12-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0045_remove_userleague_is_retained"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="feed_detail",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="feed",
            name="feed_type",
            field=models.CharField(
                choices=[
                    ("Promotion", "Promotion"),
                    ("Milestone", "Milestone"),
                    ("Streak", "Streak"),
                    ("Prize", "Prize"),
                    ("activity", "Activity"),
                ],
                max_length=30,
            ),
        ),
    ]
