# Generated by Django 5.1.1 on 2024-12-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0046_feed_feed_detail_alter_feed_feed_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="streak",
            name="currentStreakSaver",
        ),
        migrations.AddField(
            model_name="streak",
            name="streak_saved",
            field=models.BooleanField(default=False),
        ),
    ]
