# Generated by Django 5.1.1 on 2024-12-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0047_remove_streak_currentstreaksaver_streak_streak_saved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="feed_type",
            field=models.CharField(
                choices=[
                    ("Promotion", "Promotion"),
                    ("Milestone", "Milestone"),
                    ("Streak", "Streak"),
                    ("Prize", "Prize"),
                    ("activity_movement", "Activity_Movement"),
                    ("activity_mindful", "Activity_Mindful"),
                ],
                max_length=30,
            ),
        ),
    ]
