# Generated by Django 5.1.1 on 2025-01-09 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_invitation_invited_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='draw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='myapp.draw'),
        ),
    ]
