# Generated by Django 5.1.1 on 2025-01-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0050_activesession"),
    ]

    operations = [
        migrations.AddField(
            model_name="activesession",
            name="token_type",
            field=models.CharField(
                choices=[("access", "Access"), ("refresh", "Refresh")],
                default="refresh",
            ),
            preserve_default=False,
        ),
    ]
