# Generated by Django 5.1.1 on 2025-01-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0052_alter_prize_draw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activesession",
            name="token",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="activesession",
            name="token_type",
            field=models.CharField(
                choices=[("access", "Access"), ("refresh", "Refresh")], db_index=True
            ),
        ),
        migrations.AddIndex(
            model_name="activesession",
            index=models.Index(
                fields=["user", "token"], name="myapp_activ_user_id_0d8a4c_idx"
            ),
        ),
    ]
