# Generated by Django 5.1.1 on 2025-01-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0053_alter_activesession_token_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="xp",
            old_name="totalXpToday",
            new_name="xp_value",
        ),
        migrations.AlterUniqueTogether(
            name="xp",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="xp",
            name="source",
            field=models.CharField(
                choices=[
                    ("workout", "Workout"),
                    ("steps", "Steps"),
                    ("mixed", "Mixed"),
                ],
                default="mixed",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workoutactivity",
            name="activity_type",
            field=models.CharField(
                choices=[("mindfulness", "Mindfulness"), ("movement", "Movement")],
                max_length=50,
            ),
        ),
        migrations.RemoveField(
            model_name="xp",
            name="gems_awarded",
        ),
        migrations.RemoveField(
            model_name="xp",
            name="totalXpAllTime",
        ),
    ]
