# Generated by Django 5.1.1 on 2025-01-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0054_rename_totalxptoday_xp_xp_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xp",
            name="source",
            field=models.CharField(
                choices=[("workout", "Workout"), ("steps", "Steps")], max_length=20
            ),
        ),
    ]
