# Generated by Django 5.1.1 on 2025-01-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0055_alter_xp_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="xp",
            name="totalXpAllTime",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="xp",
            name="totalXpToday",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name="xp",
            index=models.Index(
                fields=["user", "date"], name="myapp_xp_user_id_f4872e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="xp",
            index=models.Index(
                fields=["user", "timeStamp"], name="myapp_xp_user_id_003dd3_idx"
            ),
        ),
    ]
