# Generated by Django 5.1.1 on 2024-12-20 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0002_usertask_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertask",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
